name: Build and upload binaries to release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  github:
    name: Publish Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Upload binary to release
        uses: ncipollo/release-action@v1

  cratesio:
    name: Publish Release to Crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to Crates.io - Library
        run: cargo publish -p bitcoin-bosd
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
